dotNet_Assignment_2/Train.AskMe.MVC/Controllers/EditorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Train.AskMe.DataBase.Library;
using TrainRule = Train.AskMe.DataBase.Library.Rule;
using Train.AskMe.BusinessLogic;


namespace Train.AskMe.MVC.Controllers
{
    public enum ListMode { PENDING, REJECTED };
    public enum ModifyMode { Edit, Delete };


    public class EditorController : Controller
    {
        private DataModel db = new DataModel();


        // GET: Edit
        public ActionResult Index(ListMode button = ListMode.PENDING)
        {
            if (button == ListMode.PENDING)
            {
                ViewBag.mode = ListMode.PENDING;

                var set = from r in db.Rules
                          where r.Status == (int)QStatus.Pending
                          select r;

                return View(set.ToList());
            }
            else
            {
                ViewBag.mode = ListMode.REJECTED;

                var set = from r in db.Rules
                          where r.Status == (int)QStatus.Rejected
                          select r;

                return View(set.ToList());
            }
        }

    }
}

dotNet_Assignment_2/Train.AskMe.MVC/Controllers/RulesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Train.AskMe.BusinessLogic;
using Train.AskMe.BusinessLogic.Utilities;
using Train.AskMe.DataBase.Library;
using TrainRule = Train.AskMe.DataBase.Library.Rule;


namespace Train.AskMe.MVC.Controllers
{
    public class RulesController : Controller
    {
        private DataService db = new DataService();

        // GET: All pending rules by default
        public ActionResult Index()
        {
            var rules = db.GetAllPendingRules();
            return View(rules.ToList());
        }

        // GET: Rules/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainRule rule = db.FindRuleById(id.Value);
            if (rule == null)
            {
                return HttpNotFound();
            }
            return View(rule);
        }

        // GET: Rules/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Question,QuestionTypeName,Answer")] TrainRule rule)
        {
            if (ModelState.IsValid)
            {
                if (!PlaceholderToken.TokenRequirementIsValid(rule))
                {
                    ModelState.AddModelError("Question", "Invalid token, please ensure you use a valid token and only one token in the question.");
                    return View(rule);
                }

                db.CreateRule((int)rule.QuestionTypeName, rule.Question, rule.Answer, User.Identity.GetUserId());
                return RedirectToAction("Index");
            }

            return View(rule);
        }

        // GET: Rules/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainRule rule = db.FindRuleById(id.Value);
            if (rule == null)
            {
                return HttpNotFound();
            }
            return View(rule);
        }

        // POST: Rules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RuleId,Question,QuestionTypeName,Answer")] TrainRule rule)
        {
            if (ModelState.IsValid)
            {
                if (!PlaceholderToken.TokenRequirementIsValid(rule))
                {
                    ModelState.AddModelError("Question", "Invalid token, please ensure you use a valid token and only one token in the question.");
                    return View(rule);
                }

                db.UpdateRule(rule.RuleId, (int)rule.QuestionTypeName, rule.Question, rule.Answer, User.Identity.GetUserId());
                return RedirectToAction("Index");
            }
            return View(rule);
        }

        // GET: Rules/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainRule rule = db.FindRuleById(id.Value);
            if (rule == null)
            {
                return HttpNotFound();
            }
            return View(rule);
        }

        // POST: Rules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.DeleteRule(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

dotNet_Assignment_2/Train.AskMe.MVC/Controllers/StopsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Train.AskMe.BusinessLogic;
using Train.AskMe.DataBase.Library;

namespace Train.AskMe.MVC.Controllers
{
    public class StopsController : Controller
    {
        private DataService db = new DataService();

        // GET: Stops
        public ActionResult Index()
        {
            return View(db.GetAllStops());
        }

        // GET: Stops/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stop stop = db.FindStop(id.Value);
            if (stop == null)
            {
                return HttpNotFound();
            }
            return View(stop);
        }

        // GET: Stops/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Stops/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StopName")] Stop stop)
        {
            if (ModelState.IsValid)
            {
                db.CreateStop(stop.StopName);
                return RedirectToAction("Index");
            }

            return View(stop);
        }

        // GET: Stops/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stop stop = db.FindStop(id.Value);
            if (stop == null)
            {
                return HttpNotFound();
            }
            return View(stop);
        }

        // POST: Stops/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StopNumber,StopName")] Stop stop)
        {
            if (ModelState.IsValid)
            {
                db.UpdateStop(stop.StopNumber, stop.StopName);
                return RedirectToAction("Index");
            }
            return View(stop);
        }

        // GET: Stops/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stop stop = db.FindStop(id.Value);
            if (stop == null)
            {
                return HttpNotFound();
            }
            return View(stop);
        }

        // POST: Stops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.DeleteStop(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

dotNet_Assignment_2/Train.AskMe.MVC/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Train.AskMe.BusinessLogic;
using Train.AskMe.DataBase.Library;
using Train.AskMe.MVC.Models;

namespace Train.AskMe.MVC.Controllers
{
    public class UsersController : Controller
    {
        private DataService db = new DataService();

        // GET: Users
        public ActionResult Index()
        {
            var users = db.GetAllUsers();
            return View(users.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.FindUserMetadata(id.Value);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.FindUserMetadata(id.Value);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,AspNetUserId,Editor,Approver,DataMaintainer")] UserViewModel user)
        {
            if (ModelState.IsValid)
            {
                db.UpdateRoles(user.AspNetUserId, user.Editor, user.Approver, user.DataMaintainer);
                return RedirectToAction("Index");
            }
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

dotNet_Assignment_2/Train.AskMe.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Train.AskMe", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @Html.Partial("_MenuPartial")
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

dotNet_Assignment_2/Train.AskMe.MVC/Views/Shared/_MenuPartial.cshtml
@using Train.AskMe.MVC
@if (Request.IsAuthenticated)
{
    <li>
        <a class="inner-menu fa fa-file-o" href="#">Rules <span class="caret"></span></a>
        <ul class="dropdown-menu">
            @if (User.Identity.IsEditor())
            {
                <li>
                    @Html.ActionLink("Create Rule", "Create", "Rules", routeValues: null, htmlAttributes: new { title = "Create a new rule" })
                </li>
                <li>
                    @Html.ActionLink("View/Edit Rules", "Index", "Rules", routeValues: null, htmlAttributes: new { title = "View all rules" })
                </li>
            }
            @if (User.Identity.IsApprover())
            {
                <li>
                    @Html.ActionLink("Approve/Reject Rule", "Index", "Approver", routeValues: null, htmlAttributes: new { title = "View Editor's Stats Report" })
                </li>
            }

        </ul>
    </li>
    if (User.Identity.IsApprover() || User.Identity.IsEditor())
    {
        <li>
            <a class="inner-menu fa fa-file-o" href="#">Reports<span class="caret"></span></a>
            <ul class="dropdown-menu">
                @if (User.Identity.IsEditor())
                {
                    <li>
                        @Html.ActionLink("My Stats", "Index", "Reports", routeValues: null, htmlAttributes: new { title = "View Editor's Report" })
                    </li>
                    <li>
                        @Html.ActionLink("Pending/Rejected Rule", "Index", "Editor", routeValues: null, htmlAttributes: new { title = "Create a new rule" })
                    </li>
                }
                @if (User.Identity.IsApprover())
                {
                    <li>
                        @Html.ActionLink("Editors Stats Report", "EditorsStats", "Reports", routeValues: null, htmlAttributes: new { title = "View Editor's Stats Report" })
                    </li>
                    <li>
                        @Html.ActionLink("Approved Report", "Approved", "Reports", routeValues: null, htmlAttributes: new { title = "View Editor's Stats Report" })
                    </li>
                }
            </ul>
        </li>
    }
    if (User.Identity.IsDataMaintainer())
    {
        <li>
            <a class="inner-menu fa fa-file-o" href="#">Admin <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li>
                    @Html.ActionLink("All Stops", "Index", "Stops", routeValues: null, htmlAttributes: new { title = "View all train stops" })
                </li>
                <li>
                    @Html.ActionLink("All Users", "Index", "Users", routeValues: null, htmlAttributes: new { title = "View/manage registered users" })
                </li>
            </ul>
        </li>
    }
}